import AccountSettings from "@/module/AccountSettings"
import AuthGuard from "@/common/components/AuthGuard"
import React from "react"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: `Account Settings - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const page = () => {
  return (
    <AuthGuard>
      <AccountSettings />
    </AuthGuard>
  )
}

export default page
