version: '3.8'
services:
  redis:
    image: redis:7.2.4
    container_name: redis
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    env_file:
      - ../../.env.development
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis_volume_data:/data
  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: unless-stopped
    ports:
      - 5540:5540
    volumes:
      - redis_insight_volume_data:/db

volumes:
  redis_volume_data:
  redis_insight_volume_data: