import PaymentHistoryGraph from "@/module/PaymentHistory/Graph"
import AuthGuard from "@/common/components/AuthGuard"
import React from "react"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: `Payment History - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const PaymentHistory = () => {
  return (
    <AuthGuard>
      <PaymentHistoryGraph />
    </AuthGuard>
  )
}

export default PaymentHistory
