import { HOST } from "@/common/constants"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import Host from "@/module/Host"

export const metadata: Metadata = {
  title: `${HOST} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const HostPage = () => {
  return <Host hostName={"John Patrick"} />
}

export default HostPage
