import AuthGuard from "@/common/components/AuthGuard"
import Notifications from "@/module/AccountSettings/Notifications"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import React from "react"

export const metadata: Metadata = {
  title: `Notifications - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const LoginSecurityPage = () => {
  return (
    <AuthGuard>
      <div className="min-h-screen">
        <Notifications />
      </div>
    </AuthGuard>
  )
}

export default LoginSecurityPage
