import CreateAccountSocial from "@/module/Authentication/CreateAccountSocial"
import { APP_NAME } from "@repo/constants"
import { CREATE_ACCOUNT } from "@/common/constants"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: `${CREATE_ACCOUNT} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const CreateAccountSocialPage = () => {
  return <CreateAccountSocial />
}

export default CreateAccountSocialPage
