import Verification from "@/module/Authentication/Verification"
import { APP_NAME } from "@repo/constants"
import { VERIFICATION } from "@/common/constants"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: `${VERIFICATION} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const VerificationPage = () => {
  return <Verification />
}

export default VerificationPage
