import React from "react"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import Conversation from "@/module/Conversation"

export const metadata: Metadata = {
  title: `Conversation - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const ConversationPage = () => {
  return <Conversation/>
}

export default ConversationPage
