version: '3.8'
services:
  es-api:
    image: jpmadrigal/es-api-dev-arm:latest
    container_name: es-api-dev-arm
    restart: unless-stopped
    env_file:
      - ../../.env
    ports:
      - 9000:9000