import AuthGuard from "@/common/components/AuthGuard"
import LoginSecurity from "@/module/AccountSettings/LoginSecurity"
import { APP_NAME } from "@repo/constants"
import { LOGIN_SECURITY } from "@/common/constants"
import { Metadata } from "next"
import React from "react"

export const metadata: Metadata = {
  title: `${LOGIN_SECURITY} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const LoginSecurityPage = () => {
  return (
    <AuthGuard>
      <LoginSecurity />
    </AuthGuard>
  )
}

export default LoginSecurityPage
