import { APP_NAME } from "@repo/constants"
import { NOTIFICATION } from "@/common/constants"
import { Metadata } from "next"
import NotificationUI from "@/module/Notification"


export const metadata: Metadata = {
  title: `${NOTIFICATION} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const NotificationPage = () => {
  return <NotificationUI />
}

export default NotificationPage
