import type { Metadata } from "next"
import { Nunito } from "next/font/google"
import "@/app/globals.css"
import React from "react"
import { APP_NAME } from "@repo/constants"

const nunito = Nunito({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: APP_NAME,
  description: `Generated by ${APP_NAME}`,
}

export default function Layout({
  children,
}: {
  readonly children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <div>{children}</div>
      </body>
    </html>
  )
}
