import Bookings from "@/module/Bookings"
import { APP_NAME } from "@repo/constants"
import { BOOKINGS } from "@/common/constants"
import { Metadata } from "next"
import { WidthWrapper } from "@/common/components/WidthWrapper"
import UserReview from "@/module/Bookings/SingleView/Review/UserReview"

export const metadata: Metadata = {
  title: `${BOOKINGS} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const UserReviewPage = () => {
  return (
    <WidthWrapper>
        <div className="my-36">
            <UserReview />
        </div>
    </WidthWrapper>
  )
}

export default UserReviewPage
