export const APP_NAME = "ExploreSiargao"
export const API_ROOT = "/api"
export const UNKNOWN_ERROR_OCCURRED = "Unknown error occurred"
export const REQUIRED_VALUE_EMPTY = "Required fields can not be empty"
export const API_URL_USERS = "/api/users"
export const API_URL_PAYMENTS = "/api/payments"
export const API_URL_COUNTRIES = "/api/countries"
export const API_URL_BOOKINGS = "/api/bookings"
