import { APP_NAME } from "@repo/constants"
import { FORGOT_PASSWORD } from "@/common/constants"
import { Metadata } from "next"
import Checkout from "@/module/Accommodation/Checkout"

export const metadata: Metadata = {
  title: `${FORGOT_PASSWORD} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const CheckoutPage = () => {
  return <Checkout />
}

export default CheckoutPage
