import React from "react"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import Cart from "@/module/Cart"

export const metadata: Metadata = {
  title: `Cart - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const CartPage = () => {
  return <Cart />
}

export default CartPage
