import SessionVerifier from "@/module/Authentication/components/SessionVerifier"
import { APP_NAME } from "@repo/constants"
import { SESSION } from "@/common/constants"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: `${SESSION} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const SessionTypePage = () => {
  return <SessionVerifier />
}

export default SessionTypePage
