import AuthGuard from "@/common/components/AuthGuard"
import React from "react"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import EarningDateTableTab from "@/module/Host/Earnings/EarningDateTableTab"

export const metadata: Metadata = {
  title: `Earnings - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const EarningDateTableTabPage = () => {
  return (
    <AuthGuard>
      <EarningDateTableTab />
    </AuthGuard>
  )
}

export default EarningDateTableTabPage
