import SuccessPayment from "@/module/Bookings/SuccessPayment"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: `Success Payment - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const SuccessPaymentPage = () => {
  return <SuccessPayment />
}

export default SuccessPaymentPage
