export const API_ROOT = '/api'
export const UNKNOWN_ERROR_OCCURRED = 'Unknown error occurred'
export const REQUIRED_VALUE_EMPTY = 'Required fields can not be empty'
export const API_URL_USERS = '/api/users'
export const ENV_PROD = 'production'
export const ENV_DEV = 'development'
