import ForgotPassword from "@/module/Authentication/ForgotPassword"
import { APP_NAME } from "@repo/constants"
import { FORGOT_PASSWORD } from "@/common/constants"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: `${FORGOT_PASSWORD} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const ForgotPasswordPage = () => {
  return <ForgotPassword />
}

export default ForgotPasswordPage
