import YourPayments from "@/module/AccountSettings/PaymentPayout/YourPayments"
import AuthGuard from "@/common/components/AuthGuard"
import { APP_NAME } from "@repo/constants"
import { YOUR_PAYMENTS } from "@/common/constants"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: `${YOUR_PAYMENTS} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const YourPaymentsPage = () => {
  return (
    <AuthGuard>
      <YourPayments />
    </AuthGuard>
  )
}

export default YourPaymentsPage
