import AuthGuard from "@/common/components/AuthGuard"
import PersonalInfo from "@/module/AccountSettings/PersonalInfo"
import { APP_NAME } from "@repo/constants"
import { PERSONAL_INFO } from "@/common/constants"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: `${PERSONAL_INFO} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const PersonalInfoPage = () => {
  return (
    <AuthGuard>
      <PersonalInfo />
    </AuthGuard>
  )
}

export default PersonalInfoPage
