import Gift from "@/module/Gift"
import { APP_NAME } from "@repo/constants"
import { GIFT } from "@/common/constants"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: `${GIFT} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const GiftPage = () => {
  return <Gift />
}

export default GiftPage
