import Earnings from "@/module/Host/Earnings"
import AuthGuard from "@/common/components/AuthGuard"
import React from "react"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: `Earnings - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const HostEarningsPage = () => {
  return (
    <AuthGuard>
      <Earnings />
    </AuthGuard>
  );
}

export default HostEarningsPage
