import Login from "@/module/Authentication/Login"
import { APP_NAME } from "@repo/constants"
import { LOGIN } from "@/common/constants"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: `${LOGIN} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const LoginPage = () => {
  return <Login />
}

export default LoginPage
