import PaymentPayout from "@/module/AccountSettings/PaymentPayout"
import AuthGuard from "@/common/components/AuthGuard"
import { APP_NAME } from "@repo/constants"
import { PAYMENTS_PAYOUTS } from "@/common/constants"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: `${PAYMENTS_PAYOUTS} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const PaymentPayoutPage = () => {
  return (
    <AuthGuard>
      <PaymentPayout />
    </AuthGuard>
  )
}

export default PaymentPayoutPage
