import { PAYMENT_HISTORY } from "@/common/constants"
import Graph from "@/module/Host/PaymentHistory/components/Graph"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: `${PAYMENT_HISTORY} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const GraphPage = () => {
  return <Graph />
}

export default GraphPage
