import { APP_NAME } from "@repo/constants"
import { PROFILE } from "@/common/constants"
import { Metadata } from "next"
import Profile from "@/module/Profile"

export const metadata: Metadata = {
  title: `${PROFILE} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const HostProfilePage = () => {
  return <Profile />
}

export default HostProfilePage
