import type { Metadata } from "next"
import { Nunito } from "next/font/google"
import "@/app/globals.css"
import QueryClientWrapper from "@/common/components/QueryClientWrapper"
import GlobalModalWrapper from "@/common/components/GlobalModalWrapper"
import { Toaster } from "react-hot-toast"
import React from "react"
import { getServerSession } from "next-auth/next"
import { SessionProvider } from "@/common/components/SessionProvider"
import { LOGO_SINGLE_IMAGE } from "@/common/constants/index"
import authOptions from "@/common/helpers/authOptions"
import { APP_NAME } from "@repo/constants"
import BottomNavBar from "@/module/Authentication/components/BottomNavBar"
import HeaderHost from "@/module/Host/components/HeaderHost"
import HostSideBar from "@/common/components/HostSidebar"
import {
  LucideBarChart,
  LucideCreditCard,
  LucideFilePen,
  LucideStar,
} from "lucide-react"

const topLinks = [
  {
    title: "Listing",
    icon: <LucideFilePen />,
    link: "/earnings",
    isSelected: true,
  },
  {
    title: "Earnings",
    icon: <LucideBarChart />,
    link: "/earnings",
    isSelected: false,
  },
  {
    title: "Payment History",
    icon: <LucideCreditCard />,
    link: "/earnings",
    isSelected: false,
  },
  {
    title: "Reviews",
    icon: <LucideStar />,
    link: "/earnings",
    isSelected: false,
  },
]

const bottomLinks = [
  {
    title: "Documentation",
    link: "/documentation",
  },
  {
    title: "Share feedback",
    link: "/feedback",
  },
  {
    title: "Join our discord",
    link: "/discord",
  },
]
const nunito = Nunito({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: APP_NAME,
  description: `Generated by ${APP_NAME}`,
}

export default async function HostLayout({
  children,
}: {
  readonly children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <link rel="icon" type="image/x-icon" href={LOGO_SINGLE_IMAGE} />
      <body className={nunito.className}>
        <Toaster />
        <SessionProvider session={session}>
          <QueryClientWrapper>
            <GlobalModalWrapper>
              <HeaderHost headerType={"Hosting Account"} />
              <HostSideBar topLinks={topLinks} bottomLinks={bottomLinks}>
                <div className="min-h-screen">{children}</div>
              </HostSideBar>
            </GlobalModalWrapper>
            <BottomNavBar />
          </QueryClientWrapper>
        </SessionProvider>
      </body>
    </html>
  )
}
