import AuthGuard from "@/common/components/AuthGuard"
import GlobalPreferences from "@/module/AccountSettings/GlobalPreferences"
import { APP_NAME } from "@repo/constants"
import { GLOBAL_PREFERENCES } from "@/common/constants"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: `${GLOBAL_PREFERENCES} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const GlobalPreferencePage = () => {
  return (
    <AuthGuard>
      <GlobalPreferences />
    </AuthGuard>
  )
}

export default GlobalPreferencePage
