import AuthGuard from "@/common/components/AuthGuard"
import Taxes from "@/module/AccountSettings/Taxes"
import { APP_NAME } from "@repo/constants"
import { TAXES } from "@/common/constants"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: `${TAXES} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const TaxesPage = () => {
  return (
    <AuthGuard>
      <Taxes />
    </AuthGuard>
  )
}

export default TaxesPage
