import { APP_NAME } from "@repo/constants"
import { HOST_PROFILE } from "@/common/constants"
import { Metadata } from "next"
import HostProfile from "../../module/HostProfile"

export const metadata: Metadata = {
  title: `${HOST_PROFILE} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const HostProfilePage = () => {
  return <HostProfile />
}

export default HostProfilePage
