export const reviews = [
  {
    id: 2,
    rate: 5,
    comment: 'Great location, amazing amenities!',
    listing: {
      image: '2.jpg',
      title: 'Luxury Beachfront Villa',
      hostedById: 1,
    },
    reviewedBy: 'Alice Smith',
    reply: {
      name: 'John Doe',
      reply: 'Thank you for the kind words!',
      createdAt: '2024-03-01T08:00:00.000Z',
    },
    createdAt: '2024-02-28T15:30:00.000Z',
  },
  {
    id: 3,
    rate: 4,
    comment: 'Cozy atmosphere, friendly hosts.',
    listing: {
      image: '3.jpg',
      title: 'Rustic Mountain Cabin',
      hostedById: 12,
    },
    reviewedBy: 'David Johnson',
    reply: {
      name: 'Emily Williams',
      reply: 'Glad you enjoyed your stay!',
      createdAt: '2024-03-02T10:45:00.000Z',
    },
    createdAt: '2024-02-29T12:15:00.000Z',
  },
  {
    id: 4,
    rate: 5,
    comment: 'Stunning views, wonderful experience!',
    listing: {
      image: '4.jpg',
      title: 'Secluded Mountain Retreat',
      hostedById: 1,
    },
    reviewedBy: 'Michael Brown',
    reply: {
      name: 'Olivia Wilson',
      reply: 'Thank you for your kind review!',
      createdAt: '2024-03-03T14:20:00.000Z',
    },
    createdAt: '2024-03-01T16:40:00.000Z',
  },
  {
    id: 5,
    rate: 3,
    comment: 'Average stay, could be improved.',
    listing: {
      image: '5.jpg',
      title: 'Urban Loft in the City',
      hostedById: 9,
    },
    reviewedBy: 'Jessica Martinez',
    reply: {
      name: 'William Taylor',
      reply: 'We appreciate your feedback!',
      createdAt: '2024-03-04T09:00:00.000Z',
    },
    createdAt: '2024-03-02T09:30:00.000Z',
  },
  {
    id: 6,
    rate: 4,
    comment: 'Nice place, clean and comfortable.',
    listing: {
      image: '6.jpg',
      title: 'Modern Apartment Downtown',
      hostedById: 1,
    },
    reviewedBy: 'Daniel Garcia',
    reply: {
      name: 'Sophia Rodriguez',
      reply: 'Thank you for staying with us!',
      createdAt: '2024-03-05T11:15:00.000Z',
    },
    createdAt: '2024-03-03T11:45:00.000Z',
  },
  {
    id: 7,
    rate: 5,
    comment: 'Absolutely loved it! Will definitely come back.',
    listing: {
      image: '7.jpg',
      title: 'Charming Cottage by the Lake',
      hostedById: 1,
    },
    reviewedBy: 'Emma Wilson',
    reply: {
      name: 'Liam Anderson',
      reply: 'Looking forward to your next visit!',
      createdAt: '2024-03-06T12:30:00.000Z',
    },
    createdAt: '2024-03-04T13:00:00.000Z',
  },
  {
    id: 8,
    rate: 3,
    comment: 'Decent stay, but could use some improvements.',
    listing: {
      image: '8.jpg',
      title: 'Suburban Family Home',
      hostedById: 2,
    },
    reviewedBy: 'Mia Davis',
    reply: {
      name: 'Noah Thompson',
      reply: "Thank you for your feedback. We'll work on it!",
      createdAt: '2024-03-07T15:45:00.000Z',
    },
    createdAt: '2024-03-05T16:20:00.000Z',
  },
  {
    id: 9,
    rate: 4,
    comment: 'Lovely place, enjoyed every moment.',
    listing: {
      image: '9.jpg',
      title: 'Quaint Countryside Cottage',
      hostedById: 2,
    },
    reviewedBy: 'Ava Clark',
    reply: {
      name: 'Ethan Harris',
      reply: 'Thank you for your kind words!',
      createdAt: '2024-03-08T17:30:00.000Z',
    },
    createdAt: '2024-03-06T18:00:00.000Z',
  },
  {
    id: 10,
    rate: 3,
    comment: 'Not bad, but nothing extraordinary either.',
    listing: {
      image: '10.jpg',
      title: 'Cozy Studio Apartment',
      hostedById: 2,
    },
    reviewedBy: 'Liam Thompson',
    reply: {
      name: 'Ava Wilson',
      reply: 'We appreciate your feedback!',
      createdAt: '2024-03-09T09:00:00.000Z',
    },
    createdAt: '2024-03-07T09:30:00.000Z',
  },
  {
    id: 11,
    rate: 4,
    comment: 'Had a pleasant stay, would recommend.',
    listing: {
      image: '11.jpg',
      title: 'Spacious Loft in the City',
      hostedById: 2,
    },
    reviewedBy: 'Ethan Martinez',
    reply: {
      name: 'Mia Davis',
      reply: 'Thank you for your recommendation!',
      createdAt: '2024-03-10T10:30:00.000Z',
    },
    createdAt: '2024-03-08T11:00:00.000Z',
  },
  {
    id: 12,
    rate: 5,
    comment: 'Absolutely stunning property!',
    listing: {
      image: '12.jpg',
      title: 'Historic Mansion Estate',
      hostedById: 3,
    },
    reviewedBy: 'Aiden Thomas',
    reply: {
      name: 'Olivia Wilson',
      reply: "We're glad you enjoyed your stay!",
      createdAt: '2024-03-11T12:45:00.000Z',
    },
    createdAt: '2024-03-09T13:00:00.000Z',
  },
  {
    id: 13,
    rate: 3,
    comment: 'Not bad, but could be cleaner.',
    listing: {
      image: '13.jpg',
      title: 'Sunny Beach House',
      hostedById: 3,
    },
    reviewedBy: 'Lucas Garcia',
    reply: {
      name: 'Sophia Brown',
      reply: "Thank you for your feedback. We'll improve!",
      createdAt: '2024-03-12T14:30:00.000Z',
    },
    createdAt: '2024-03-10T15:00:00.000Z',
  },
  {
    id: 14,
    rate: 4,
    comment: 'Great value for the price.',
    listing: {
      image: '14.jpg',
      title: 'Cozy Cabin in the Woods',
      hostedById: 3,
    },
    reviewedBy: 'Benjamin Lee',
    reply: {
      name: 'Emma Thompson',
      reply: "We're glad you enjoyed your stay!",
      createdAt: '2024-03-13T16:45:00.000Z',
    },
    createdAt: '2024-03-11T17:00:00.000Z',
  },
  {
    id: 15,
    rate: 3,
    comment: 'Average experience, nothing special.',
    listing: {
      image: '15.jpg',
      title: 'Studio Apartment Downtown',
      hostedById: 3,
    },
    reviewedBy: 'Hannah Roberts',
    reply: {
      name: 'William Taylor',
      reply: 'Thank you for your feedback!',
      createdAt: '2024-03-14T09:30:00.000Z',
    },
    createdAt: '2024-03-12T10:00:00.000Z',
  },
  {
    id: 16,
    rate: 5,
    comment: 'Amazing place, exceeded expectations!',
    listing: {
      image: '16.jpg',
      title: 'Luxury Penthouse Suite',
      hostedById: 3,
    },
    reviewedBy: 'Isabella White',
    reply: {
      name: 'Daniel Harris',
      reply: "We're thrilled to hear that!",
      createdAt: '2024-03-15T11:15:00.000Z',
    },
    createdAt: '2024-03-09T12:00:00.000Z',
  },
  {
    id: 17,
    rate: 4,
    comment: 'Enjoyable stay, would recommend.',
    listing: {
      image: '17.jpg',
      title: 'Modern Loft with City Views',
      hostedById: 3,
    },
    reviewedBy: 'Alexander Martinez',
    reply: {
      name: 'Emily Johnson',
      reply: 'Thank you for your recommendation!',
      createdAt: '2024-03-16T13:30:00.000Z',
    },
    createdAt: '2024-03-14T14:00:00.000Z',
  },
  {
    id: 18,
    rate: 3,
    comment: 'Decent stay, nothing extraordinary.',
    listing: {
      image: '18.jpg',
      title: 'Cozy Cabin Retreat',
      hostedById: 4,
    },
    reviewedBy: 'Charlotte Brown',
    reply: {
      name: 'Noah Anderson',
      reply: 'Thank you for your feedback!',
      createdAt: '2024-03-17T15:45:00.000Z',
    },
    createdAt: '2024-03-15T16:00:00.000Z',
  },
  {
    id: 19,
    rate: 4,
    comment: 'Lovely place, perfect for a weekend getaway.',
    listing: {
      image: '19.jpg',
      title: 'Riverside Cottage',
      hostedById: 4,
    },
    reviewedBy: 'Amelia Taylor',
    reply: {
      name: 'Jacob Harris',
      reply: "We're glad you enjoyed your stay!",
      createdAt: '2024-03-18T17:30:00.000Z',
    },
    createdAt: '2024-03-16T18:00:00.000Z',
  },
  {
    id: 20,
    rate: 4,
    comment: 'Fantastic view from the balcony!',
    listing: {
      image: '20.jpg',
      title: 'City Skyline Apartment',
      hostedById: 4,
    },
    reviewedBy: 'Sophia Brown',
    reply: {
      name: 'Jacob Anderson',
      reply: "We're glad you enjoyed the view!",
      createdAt: '2024-03-03T09:30:00.000Z',
    },
    createdAt: '2024-03-01T18:45:00.000Z',
  },
]
