import AuthGuard from "@/common/components/AuthGuard"
import React from "react"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import SingleView from "@/module/Bookings/SingleView"
import { getRequest } from "@/common/helpers/getRequest"
import { ACCOMMODATION } from "@/common/constants"
import { T_Listing, Z_Listing } from "@repo/contract"

export const metadata: Metadata = {
  title: `${ACCOMMODATION} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const AccommodationPage = async () => {
  const listing = await getRequest(`/listings/3`)
  const validateData = Z_Listing.safeParseAsync(listing.item)
  console.log((await validateData).success)
  return (
    <AuthGuard>
      <SingleView listing={listing.item as T_Listing} />
    </AuthGuard>
  )
}

export default AccommodationPage
