import AuthGuard from "@/common/components/AuthGuard"
import React from "react"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import SingleView from "@/module/Bookings/SingleView"
import { getRequest } from "@/common/helpers/getRequest"
import { ACCOMMODATION } from "@/common/constants"

export const metadata: Metadata = {
  title: `${ACCOMMODATION} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const AccommodationPage = async () => {
  const booking = await getRequest(`/listings/1`)
  console.log("listings server", booking)
  return (
    <AuthGuard>
      <SingleView />
    </AuthGuard>
  )
}

export default AccommodationPage
