import AuthGuard from "@/common/components/AuthGuard"
import React from "react"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import SingleView from "@/module/Bookings/SingleView"
import { getRequest } from "@/common/helpers/getRequest"
import { ACCOMMODATION } from "@/common/constants"
import { T_Listing, Z_Listing } from "@repo/contract"

export const metadata: Metadata = {
  title: `${ACCOMMODATION} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const AccommodationPage = async () => {
  const listing = await getRequest(`/listings/1`)
  // console.log("listings server", listing)
  const validateData = Z_Listing.safeParse(listing);
  console.log("validateData", validateData.error)
  return (
    <AuthGuard>
      <SingleView listing={listing.item as T_Listing} />
    </AuthGuard>
  )
}

export default AccommodationPage
