import AuthGuard from "@/common/components/AuthGuard"
import React from "react"
import { APP_NAME } from "@repo/constants"
import { Metadata } from "next"
import EarningDateGraphTab from "@/module/Host/Earnings/EarningDateGraphTab"

export const metadata: Metadata = {
  title: `Earnings - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const EarningsDateGraphTabPage = () => {
  return (
    <AuthGuard>
      <EarningDateGraphTab />
    </AuthGuard>
  )
}

export default EarningsDateGraphTabPage

