import NewPassword from "@/module/Authentication/NewPassword"
import { APP_NAME } from "@repo/constants"
import { NEW_PASSWORD } from "@/common/constants"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: `${NEW_PASSWORD} - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
}

const NewPasswordPage = () => {
  return <NewPassword />
}

export default NewPasswordPage
